### PR TITLE
Do not send error if HTTP connection is closed

### LINKED ISSUE #359: Error [ERR_STREAM_WRITE_AFTER_END] caused bridge crash on SlackHookHandler.handleEvent
```
Feb 26 22:10:02 lethe docker-slack-bridge[768]: Feb-26 22:10:02.903 INFO bridge ::ffff:10.2.4.64 - - [26/Feb/2020:22:10:02 +0000] "GET /metrics HTTP/1.1" 200 15431 "-" "Prometheus/2.3.2"
Feb 26 22:10:02 lethe docker-slack-bridge[768]: 
Feb 26 22:10:03 lethe docker-slack-bridge[768]: Feb-26 22:10:03.066 DEBUG SlackHookHandler POST /YmV23WLl2RlLEVq2d99qawBaPJ0zcgV4 bodyLen=129
Feb 26 22:10:03 lethe docker-slack-bridge[768]: Feb-26 22:10:03.067 ERROR SlackHookHandler SlackHookHandler failed: TypeError: Cannot read property 'toUpperCase' of undefined
Feb 26 22:10:03 lethe docker-slack-bridge[768]:     at SlackHookHandler.handleEvent (/usr/src/app/lib/SlackHookHandler.js:113:74)
Feb 26 22:10:03 lethe docker-slack-bridge[768]:     at IncomingMessage.<anonymous> (/usr/src/app/lib/SlackHookHandler.js:74:26)
Feb 26 22:10:03 lethe docker-slack-bridge[768]:     at IncomingMessage.emit (events.js:215:7)
Feb 26 22:10:03 lethe docker-slack-bridge[768]:     at endReadableNT (_stream_readable.js:1183:12)
Feb 26 22:10:03 lethe docker-slack-bridge[768]:     at processTicksAndRejections (internal/process/task_queues.js:80:21)
Feb 26 22:10:03 lethe docker-slack-bridge[768]: events.js:187
Feb 26 22:10:03 lethe docker-slack-bridge[768]:       throw er; // Unhandled 'error' event
Feb 26 22:10:03 lethe docker-slack-bridge[768]:       ^
Feb 26 22:10:03 lethe docker-slack-bridge[768]: 
Feb 26 22:10:03 lethe docker-slack-bridge[768]: Error [ERR_STREAM_WRITE_AFTER_END]: write after end
Feb 26 22:10:03 lethe docker-slack-bridge[768]:     at write_ (_http_outgoing.js:594:17)
Feb 26 22:10:03 lethe docker-slack-bridge[768]:     at ServerResponse.write (_http_outgoing.js:586:15)
Feb 26 22:10:03 lethe docker-slack-bridge[768]:     at IncomingMessage.<anonymous> (/usr/src/app/lib/SlackHookHandler.js:87:25)
Feb 26 22:10:03 lethe docker-slack-bridge[768]:     at IncomingMessage.emit (events.js:215:7)
Feb 26 22:10:03 lethe docker-slack-bridge[768]:     at endReadableNT (_stream_readable.js:1183:12)
Feb 26 22:10:03 lethe docker-slack-bridge[768]:     at processTicksAndRejections (internal/process/task_queues.js:80:21)
Feb 26 22:10:03 lethe docker-slack-bridge[768]: Emitted 'error' event on ServerResponse instance at:
Feb 26 22:10:03 lethe docker-slack-bridge[768]:     at writeAfterEndNT (_http_outgoing.js:649:7)
Feb 26 22:10:03 lethe docker-slack-bridge[768]:     at processTicksAndRejections (internal/process/task_queues.js:81:21) {
Feb 26 22:10:03 lethe docker-slack-bridge[768]:   code: 'ERR_STREAM_WRITE_AFTER_END'
Feb 26 22:10:03 lethe docker-slack-bridge[768]: }
Feb 26 22:10:04 lethe docker-slack-bridge[768]: Feb-26 22:10:04.788 INFO Main Enabled RTM
Feb 26 22:10:04 lethe docker-slack-bridge[768]: Feb-26 22:10:04.809 INFO Main Loading databases
Feb 26 22:10:04 lethe docker-slack-bridge[768]: (node:1) DeprecationWarning: prom-client - Passing a non-object to metrics constructor is deprecated
```

### PR DESCRIPTION
**Pull request by Half-Shot**
Fixes #359

### CODE REVIEW

File: src/SlackHookHandler.ts [hunk 1]
```diff
@@ -107,6 +108,9 @@ export class SlackHookHandler extends BaseSlackHandler {
                 }
             } catch (e) {
                 log.error("SlackHookHandler failed:", e);
+                if (res.finished) {
```
Comment (jaller94) [inline src/SlackHookHandler.ts:111]: Above this line should be a comment saying "Do not send error if HTTP connection is closed".

If the issue was important, maybe link it.
