### PR TITLE
User correct Matrix accounts when redacting events

### LINKED ISSUE #766: Loss of messages after a redacted events
Thread messages were no longer displayed after an Forbidden exception was thrown.

This is the correlation between the stacktrace and the time of the last comment in the thread.

You can get more context on these two rooms:
* Slack link: https://adoptium.slack.com/archives/C09NW3L2J/p1691496235571849
* Matrix: [https://chat.eclipse.org/#/room/!fVoSNgMwqogKMyGzoF:matrix.eclipse.org/$3NWVr4StBu4ho1E9sWHUDV5lajjQ2oJwV_VrHJbN_rE?via=matrix.eclipse.org](https://chat.eclipse.org/#/room/!fVoSNgMwqogKMyGzoF:matrix.eclipse.org/%243NWVr4StBu4ho1E9sWHUDV5lajjQ2oJwV_VrHJbN_rE?via=matrix.eclipse.org)

I don't know if the redact event comes from matrix or slack.

The stacktrace: 
```
ERROR 12:18:04:410 [MatrixHttpClient] (REQ-2365) {
errcode: 'M_FORBIDDEN',
error: "You don't have permission to redact events"
}
WARN 12:18:04:410 [SlackEventHandler] Error when handing event: MatrixError: M_FORBIDDEN: You don't have permission to redact events
at doHttpRequest (/usr/src/app/node_modules/matrix-bot-sdk/lib/http.js:95:15)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async descriptor.value (/usr/src/app/node_modules/matrix-bot-sdk/lib/metrics/decorators.js:19:32)
at async descriptor.value (/usr/src/app/node_modules/matrix-bot-sdk/lib/metrics/decorators.js:19:32)
at async SlackRTMHandler.handleMessageEvent (/usr/src/app/lib/SlackEventHandler.js:204:17)
at async SlackRTMHandler.handleEvent (/usr/src/app/lib/SlackEventHandler.js:99:17)
at async SlackRTMHandler.handle (/usr/src/app/lib/SlackEventHandler.js:52:17) {
body: {
errcode: 'M_FORBIDDEN',
error: "You don't have permission to redact events"
},
statusCode: 403,
errcode: 'M_FORBIDDEN',
error: "You don't have permission to redact events",
retryAfterMs: undefined
}
```

### PR DESCRIPTION
**Pull request by tadzik**
Fixes https://github.com/matrix-org/matrix-appservice-slack/issues/766

For events sent from Slack and later deleted from Slack, we use the same Slack Ghost that sent the message – this alleviates the need for an elevated Power Level.

For events sent from Matrix and deleted from Slack, we try to use our bot account. This does require us to have a sufficient power level, so we try to be helpful in the logs if we don't.

Note: Slack doesn't tell us who deleted the message, so we can't bridge that precisely – the sender of a redact event is just our best effort.

### CODE REVIEW

File: src/BaseSlackHandler.ts [hunk 1]
```diff
@@ -50,6 +50,7 @@ export interface ISlackEventMessageAttachment {
 }
 
 export interface ISlackMessageEvent extends ISlackEvent {
+    team?: string;
```
Comment (tadzik) [inline src/BaseSlackHandler.ts:53]: I have not actually seen `team_id` in incoming Slack messages, and the only place I see it used is when it's artificially assigned to in SlackRTMHandler – perhaps it's an error in our typing?

File: src/SlackEventHandler.ts [hunk 2]
```diff
@@ -291,8 +291,29 @@ export class SlackEventHandler extends BaseSlackHandler {
...
             if (originalEvent) {
-                const botClient = this.main.botIntent.matrixClient;
-                await botClient.redactEvent(originalEvent.roomId, originalEvent.eventId);
+                const previousMessage = msg.previous_message;
+                if (!previousMessage) {
+                    log.error("Cannot delete message with no previous_message:", msg);
+                    return;
+                }
+                if (previousMessage.subtype === 'bot_message') {
+                    // Sent from Matrix, try to remove it with our bot account
```
Comment (tadzik) [inline src/SlackEventHandler.ts]: Hrm, should actually check if it's indeed *our* bot account...

File: src/SlackEventHandler.ts [hunk 3]
```diff
@@ -291,8 +291,29 @@ export class SlackEventHandler extends BaseSlackHandler {
...
+                        return;
+                    }
+                }
+                else if (!previousMessage.user) {
+                    log.error("Cannot redact Slack message if we don't know the original sender:", previousMessage);
+                    return;
+                }
+                else {
+                    const ghost = await this.main.ghostStore.get(previousMessage.user, previousMessage.team_domain, previousMessage.team);
+                    await ghost.redactEvent(originalEvent.roomId, originalEvent.eventId);
```
Comment (Half-Shot) [inline src/SlackEventHandler.ts]: Should we try with the botClient if this fails, as a fallback?

File: src/SlackEventHandler.ts [hunk 4]
```diff
@@ -291,8 +291,29 @@ export class SlackEventHandler extends BaseSlackHandler {
...
+                    try {
+                        const botClient = this.main.botIntent.matrixClient;
+                        await botClient.redactEvent(originalEvent.roomId, originalEvent.eventId, "Deleted on Slack");
+                    } catch (err) {
+                        log.error("Failed to remove message", previousMessage, "with our Matrix bot: insufficient power level? Error:", err);
+                        return;
+                    }
+                }
+                else if (!previousMessage.user) {
+                    log.error("Cannot redact Slack message if we don't know the original sender:", previousMessage);
```
Comment (Half-Shot) [inline src/SlackEventHandler.ts]: can we just use the botClient?

File: src/BaseSlackHandler.ts (hunk 1 above)
Comment (Half-Shot) [reply src/BaseSlackHandler.ts:53]: I don't really remember when this was introduced, it's possible it's invalid and team_id is the right one.

**Review by Half-Shot — CHANGES_REQUESTED** [review]
Some thoughts.

File: src/SlackEventHandler.ts (hunk 3 above)
Comment (tadzik) [reply src/SlackEventHandler.ts]: Done in b4f2911c5a102b72825db225b3129887523bcdf0

File: src/SlackEventHandler.ts (hunk 4 above)
Comment (tadzik) [reply src/SlackEventHandler.ts]: Done in b4f2911c5a102b72825db225b3129887523bcdf0; this has a side effect of us trying to delete messages sent by originally-Matrix users with the slack bot – which probably makes sense.

**Review by Half-Shot — CHANGES_REQUESTED** [review]
Good to go after changelog.

**Comment by tadzik** [comment]
> Good to go after changelog.

Added in e2df892
