### PR TITLE
Fix metrics bug: Month has been off by one (e.g. January = 0)

### LINKED ISSUE #552: ERROR BridgedRoom Error storing activity metrics error: date/time field value out of range: "2021-0-4"
**Describe the bug**

Happends on latest master (which correlates to 1.6.1 at the moment) and latest develop branch. Sending any messages M>S does not work, instead we get this error on bridge log:

```
tammi 04 12:58:18 morpheus node[2431]: Jan-4 12:58:18.672 INFO Main Handling matrix room message $b2JwwtwZ4ueUORQtcBwk5He_BJBmHfXNfvK4ayC7UG4 !OwkWEsdHkzXRAQkApj:hacklab.fi
tammi 04 12:58:18 morpheus node[2431]: Jan-4 12:58:18.998 ERROR BridgedRoom Error storing activity metrics error: date/time field value out of range: "2021-0-4"
tammi 04 12:58:18 morpheus node[2431]:     at Parser.parseErrorMessage (/opt/slackbot/matrix-appservice-slack/node_modules/pg-protocol/dist/parser.js:278:15)
tammi 04 12:58:18 morpheus node[2431]:     at Parser.handlePacket (/opt/slackbot/matrix-appservice-slack/node_modules/pg-protocol/dist/parser.js:126:29)
tammi 04 12:58:18 morpheus node[2431]:     at Parser.parse (/opt/slackbot/matrix-appservice-slack/node_modules/pg-protocol/dist/parser.js:39:38)
tammi 04 12:58:18 morpheus node[2431]:     at Socket.<anonymous> (/opt/slackbot/matrix-appservice-slack/node_modules/pg-protocol/dist/index.js:8:42)
tammi 04 12:58:18 morpheus node[2431]:     at Socket.emit (events.js:314:20)
tammi 04 12:58:18 morpheus node[2431]:     at addChunk (_stream_readable.js:297:12)
tammi 04 12:58:18 morpheus node[2431]:     at readableAddChunk (_stream_readable.js:272:9)
tammi 04 12:58:18 morpheus node[2431]:     at Socket.Readable.push (_stream_readable.js:213:10)
tammi 04 12:58:18 morpheus node[2431]:     at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
tammi 04 12:58:18 morpheus node[2431]:   length: 168,
tammi 04 12:58:18 morpheus node[2431]:   severity: 'ERROR',
tammi 04 12:58:18 morpheus node[2431]:   code: '22008',
tammi 04 12:58:18 morpheus node[2431]:   detail: undefined,
tammi 04 12:58:18 morpheus node[2431]:   hint: 'Perhaps you need a different "datestyle" setting.',
tammi 04 12:58:18 morpheus node[2431]:   position: '128',
tammi 04 12:58:18 morpheus node[2431]:   internalPosition: undefined,
tammi 04 12:58:18 morpheus node[2431]:   internalQuery: undefined,
tammi 04 12:58:18 morpheus node[2431]:   where: undefined,
tammi 04 12:58:18 morpheus node[2431]:   schema: undefined,
tammi 04 12:58:18 morpheus node[2431]:   table: undefined,
tammi 04 12:58:18 morpheus node[2431]:   column: undefined,
tammi 04 12:58:18 morpheus node[2431]:   dataType: undefined,
tammi 04 12:58:18 morpheus node[2431]:   constraint: undefined,
tammi 04 12:58:18 morpheus node[2431]:   file: 'datetime.c',
tammi 04 12:58:18 morpheus node[2431]:   line: '3739',
tammi 04 12:58:18 morpheus node[2431]:   routine: 'DateTimeParseError'
tammi 04 12:58:18 morpheus node[2431]: }
tammi 04 12:58:19 morpheus node[2431]: Jan-4 12:58:19.003 INFO Main Handled $b2JwwtwZ4ueUORQtcBwk5He_BJBmHfXNfvK4ayC7UG4 (!OwkWEsdHkzXRAQkApj:hacklab.fi)
```

**To Reproduce**
1. Live in 2021 (Not entirely sure when this started, but 2021 is strong candidate)
2. See error

**Expected behavior**
Messages to work normally

Server:
Debian buster
Postgresql 13
Synapse 1.24.0

### PR DESCRIPTION
**Pull request by jaller94**
Fixes #552

Fixes months to be zero-based and migrates old data.
This bug only affects our PostgreSQL adapter. Metrics are not supported by our NeDB adapter.

### CODE REVIEW

**Review by olmari — CHANGES_REQUESTED** [review]
This fails now

```
tammi 04 14:20:39 morpheus node[4982]: Jan-4 14:20:39.562 INFO PgDatastore Updating schema to v11
tammi 04 14:20:39 morpheus node[4982]: Jan-4 14:20:39.565 WARN PgDatastore Failed to run schema v11: error: duplicate key value violates unique constraint "cons_activities_unique"
tammi 04 14:20:39 morpheus node[4982]:     at Parser.parseErrorMessage (/opt/slackbot/matrix-appservice-slack/node_modules/pg-protocol/dist/parser.js:278:15)
tammi 04 14:20:39 morpheus node[4982]:     at Parser.handlePacket (/opt/slackbot/matrix-appservice-slack/node_modules/pg-protocol/dist/parser.js:126:29)
tammi 04 14:20:39 morpheus node[4982]:     at Parser.parse (/opt/slackbot/matrix-appservice-slack/node_modules/pg-protocol/dist/parser.js:39:38)
tammi 04 14:20:39 morpheus node[4982]:     at Socket.<anonymous> (/opt/slackbot/matrix-appservice-slack/node_modules/pg-protocol/dist/index.js:8:42)
tammi 04 14:20:39 morpheus node[4982]:     at Socket.emit (events.js:314:20)
tammi 04 14:20:39 morpheus node[4982]:     at addChunk (_stream_readable.js:297:12)
tammi 04 14:20:39 morpheus node[4982]:     at readableAddChunk (_stream_readable.js:272:9)
tammi 04 14:20:39 morpheus node[4982]:     at Socket.Readable.push (_stream_readable.js:213:10)
tammi 04 14:20:39 morpheus node[4982]:     at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
tammi 04 14:20:39 morpheus node[4982]:   length: 306,
tammi 04 14:20:39 morpheus node[4982]:   severity: 'ERROR',
tammi 04 14:20:39 morpheus node[4982]:   code: '23505',
tammi 04 14:20:39 morpheus node[4982]:   detail: 'Key (user_id, room_id, date)=(@olmari:hacklab.fi, INTEG-T8sT8RWYqdXQrowuWtZZ6jxQEAcXAg9b, 2020-05-08) already exists.',
tammi 04 14:20:39 morpheus node[4982]:   hint: undefined,
tammi 04 14:20:39 morpheus node[4982]:   position: undefined,
tammi 04 14:20:39 morpheus node[4982]:   internalPosition: undefined,
tammi 04 14:20:39 morpheus node[4982]:   internalQuery: undefined,
tammi 04 14:20:39 morpheus node[4982]:   where: undefined,
tammi 04 14:20:39 morpheus node[4982]:   schema: 'public',
tammi 04 14:20:39 morpheus node[4982]:   table: 'metrics_activities',
tammi 04 14:20:39 morpheus node[4982]:   column: undefined,
tammi 04 14:20:39 morpheus node[4982]:   dataType: undefined,
tammi 04 14:20:39 morpheus node[4982]:   constraint: 'cons_activities_unique',
tammi 04 14:20:39 morpheus node[4982]:   file: 'nbtinsert.c',
tammi 04 14:20:39 morpheus node[4982]:   line: '656',
tammi 04 14:20:39 morpheus node[4982]:   routine: '_bt_check_unique'
tammi 04 14:20:39 morpheus node[4982]: }
tammi 04 14:20:39 morpheus node[4982]: Jan-4 14:20:39.565 ERROR app Failed to start: Error: Failed to update database schema
tammi 04 14:20:39 morpheus node[4982]:     at PgDatastore.ensureSchema (/opt/slackbot/matrix-appservice-slack/lib/datastore/postgres/PgDatastore.js:181:23)
tammi 04 14:20:39 morpheus node[4982]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Review by olmari — APPROVED** [review]
EDIT: This was towards the first commit, can't delete this apparently: ~~This alone works, the later added schema update fails.~~

**Comment by jaller94** [comment]
That happens when `2020-07-01` cannot be updated because `2020-08-01` already exists. I cannot tell Postgres in which order to update values nor can I temporarily disable the `UNIQUE` constraint.

The constraint now gets dropped and re-added.

File: src/datastore/postgres/schema/v11.ts [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+export const runSchema = async (db: IDatabase<unknown>): Promise<void> => {
+    // In 2020, when metrics_activities were introduced, there was a bug that caused
+    // months to be zero-based (one number lower than expected).
+    // https://github.com/matrix-org/matrix-appservice-slack/issues/552
+
+    // UNIQUE contraints cannot be deferred, so we drop it and re-add it after the migration.
+    await db.none(`
+        ALTER TABLE metrics_activities DROP CONSTRAINT cons_activities_unique;
+    
+        UPDATE metrics_activities set date = date + interval '1 month';
```
Comment (Half-Shot) [inline src/datastore/postgres/schema/v11.ts:12]: Nice :)

**Review by Half-Shot — APPROVED** [review]
Looking good!

**Review by olmari — APPROVED** [review]
PR seems now to work fully.
