### PR TITLE
Do not fail to bridge slack message if an alias doesn't exist

### LINKED ISSUE #524: Slack message can fail to bridge if transforming a channel mention fails
The bridge will try to fetch `m.room.canonical_alias` state for the room mentioned (in order to get the right alias), and if it fails to get the event then the code will throw and subsequently fail to bridge the message. This is obviously not ideal, and we should fall back to textual representation.

### PR DESCRIPTION
**Pull request by Half-Shot**
Fixes #524

### CODE REVIEW

File: src/BaseSlackHandler.ts [hunk 1]
```diff
@@ -171,11 +171,14 @@ export abstract class BaseSlackHandler {
...
-                    text = text.slice(0, match.index) + canonical.alias + text.slice(match.index + match[0].length);
-                } else {
+                try {
+                    const canonical = await client.getStateEvent(room.MatrixRoomId, "m.room.canonical_alias");
+                    if (canonical !== undefined && canonical.alias !== undefined) {
+                        text = text.slice(0, match.index) + canonical.alias + text.slice(match.index + match[0].length);
+                    }
+                } catch (ex) {
                     // If we can't find a canonical alias fall back to just the Slack channel name.
+                    log.debug(`Room ${room.MatrixRoomId} does not have a canonical alias set.`);
```
Comment (jaller94) [inline src/BaseSlackHandler.ts:181]: Lets log ex here. The error may not come from the promise failing as there's more in the try block.

"have an alias set" is ambiguous as "set" can be a verb or a noun.

```suggestion
                    log.debug(`Room ${room.MatrixRoomId} does not have a canonical alias.`, ex);
```

**Review by jaller94 — APPROVED** [review]
Looks good to me, with one exception.
